### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rlucian** [jenssegers/imagehash#11]
great library, need to say that first.

Scenario:
If we have a large library of pictures, we can calculate and store the ahash, dhash and phash in an mysql table. 
Then, for any new picture, we can calculate the hash, but in order to see if we already have something similar in the db, we need to calculate the distance between the new pic and each of the hashes stored in the db. 
Is there any way to translate the comparison function to a mysql function, so that we would "select" the values in the db that are near the hash we are checking?

**Comment by jenssegers** [comment]
There is, but on mysql it can not use indexes. Check out https://jenssegers.com/61/perceptual-image-hashes for the query at the bottom
