### ISSUE TITLE
Why returns hex hash in last version?

### ISSUE THREAD

**Issue by memboc** [jenssegers/imagehash#12]
In previous version method ImageHash->hash() returns an integer? Now it hex value in type "string". I have database of hashes in BIGINT type, and search in integer field is faster than string.

**Comment by jenssegers** [comment]
I didn't like how PHP converted the 64 bit string to both positive and negative numbers. I figured that these hashes are a nicer way of having portability between different languages that handle 64 bit integers in different ways.

**Comment by memboc** [comment]
For compatibility it should be optional parameter. At the moment, I am forced to roll back to old version in my project

**Comment by jenssegers** [comment]
I'll look into adding an option to return decimals :)

**Comment by memboc** [comment]
thanks :+1:

**Comment by lstrojny** [comment]
There is an `is_int()` check before `dechex()`. Any way an implementation would *not* return an int?

**Comment by jenssegers** [comment]
@lstrojny Not at this moment.

**Comment by jenssegers** [comment]
I added a second constructor parameter to switch out the hashing between hex and decimal.
