### ISSUE TITLE
installation errors at UBUNTU 16

### ISSUE THREAD

**Issue by ppKrauss** [jenssegers/imagehash#20]
on `composer require jenssegers/imagehash` the first problem, that need some FAQ was
```
file_put_contents(/home/peter/.composer/cache/repo/https---packagist.org/p-provider-2016-10.json): failed to open stream: Permission denied
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```
Them, suppose fix by (not recommended) `sudo` ... Ok, no permission error, but a new error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jenssegers/imagehash dev-master -> satisfiable by jenssegers/imagehash[dev-master].
    - Can only install one of: jenssegers/imagehash[v0.4.1, dev-master].
    - Installation request for jenssegers/imagehash ^0.4.1 -> satisfiable by jenssegers/imagehash[v0.4.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by jenssegers** [comment]
Looks like an issue with your php installation.

**Comment by ppKrauss** [comment]
Ok, a workaround resolved.. Now the problem is about `use` clause position and path, at my `projetc/src` folder where I run `composer require jenssegers/imagehash` now I have as `ls`:
```
composer.json  composer.lock   sync.php  
vendor
  autoload.php  
  composer 
  jenssegers
       imagehash
          composer.json  README.md  
          src
              ImageHash.php  Implementation.php  Implementations
```

Them, at my projects folder I run `php sync.php` ... ERROR

  **PHP Fatal error:  Uncaught Error:  Class 'Jenssegers\ImageHash\ImageHash' not found**

**Comment by ppKrauss** [comment]
Ok, fixed the problem with `require __DIR__ . '/vendor/autoload.php'` ... So the real problem/suggestion is:

if you see as support, I can  add or suggest text for *"A **Dummy's** Guide To Install and use imagehash"*

**Comment by wouterds** [comment]
That's not really a problem related to this package (imho). When using a package with composer you are assumed to know at least how to include the composer autoloader.

**Comment by sppidy** [comment]
```
require __DIR__ . '/vendor/autoload.php';
$hasher = new ImageHash;
$hash = $hasher->hash('img/img1.jpg');
$hash2 = $hasher->hash('img/img2.jpg');
$distance = $hasher->distance($hash1, $hash2);
echo $distance;
```

this is my code but still iam getting this error

Fatal error: Uncaught Error: Class 'ImageHash' not found

**Comment by wouterds** [comment]
@sppidy Did you install the package?

`composer require jenssegers/imagehash`

**Comment by sppidy** [comment]
@wouterds  yes i installed it

**Comment by TOA** [comment]
@sppidy you still need to add a use statement due to namespaces. Add the following code after your require statement.

`use ImageHash;`

Also, most modern IDE's will alert you to this need and offer auto-fill capabilities. I suggest PHPStorm.
