### ISSUE TITLE
imagick implementation

### ISSUE THREAD

**Issue by Gamesh** [jenssegers/imagehash#32]
are there any plans to add perceptual hashing using imagick instead of GD?

**Comment by jenssegers** [comment]
I wasn't really planning on it. But kinda makes sense to switch out some sort of driver.

**Comment by pachico** [comment]
I might have the time to implement it during the next weeks.

**Comment by jenssegers** [comment]
I already started on an imagick branch https://github.com/jenssegers/imagehash/tree/imagick

**Comment by jenssegers** [comment]
New release: https://github.com/jenssegers/imagehash/releases/tag/v0.5.0

**Comment by Gamesh** [comment]
@jenssegers wow that was super fast, thanks a lot!
