### ISSUE TITLE
Storing Hash metadata along the hashes to enable forward-compatibility & rehashing

### ISSUE THREAD

**Issue by Lucassifoni** [jenssegers/imagehash#35]
Hi,
First of all, thanks for your recent activity, you're upgrading this so fast !

I was thinking that maybe an implementation akin to php's password_hash, password_verify, password_needs_rehash for perceptual hashes would be great.

Maybe you'll want, in x years, to migrate to 128*128 sources for the hashes, or to 256bit hashes, as hardware gains in processing power.. Or you'd like to compensate for switching from an image processing backend to another, and anticipate slightly different hashes.

Maybe along hashes could be stored backend type, sample size, and hash length information, to allow for smarter compare functions ?

The main use case would be something along those lines : 

- Given a picture, hashed on 2017/01/01, with gd, a 32x32 source, to a 64bit hash
- Given you now hash with imagemagick, a 128x128 source, to a 256bit hash because you found it provides stellar results - this is pure speculation -
- Given you trigger a massive search for potential duplicates in your database

While walking the database, each hash is compared to today's default implementation. If its hash is obsolete, you can re-hash it instantly and move on with your comparisons.

I'd be willing to work on this if it seems useful enough.
The drawbacks resides in a nonstandard perceptual hash storage, but I doubt there are standards on this matter right now.

Have a nice day !

**Comment by jenssegers** [comment]
I was recently thinking about something similar as well. But I feel like this can also be the responsibility of the developer storing it in the database, to also store the method used to generate the hash.

Probably; once implementations go towards a 1.0.0 version, they will get additional constructor parameters to tweak internals. Not sure how we can translate those to some sort of prefix.

**Comment by Lucassifoni** [comment]
You're right, getting a storable hash method in some form would be better than prefixing hashes to avoid restricting possible future interops.
Thanks for your answer!
