### ISSUE TITLE
Fatal error: echo $hash->toBin();

### ISSUE THREAD

**Issue by Ahnungsloser** [jenssegers/imagehash#53]
echo $hash->toBin(); produces fatal error ..
Fatal error: Uncaught Error: Call to undefined method Jenssegers\ImageHash\Hash::toBin()

**Comment by gorkijatt** [comment]
function name has been changed to bits
you can use `echo $hash->toBits();`

**Comment by e-edgren** [comment]
> function name has been changed to bits
> you can use `echo $hash->toBits();`

Nope. Same issue with `composer require intervention/image dev-master`: `Fatal error: Uncaught Error: Call to a member function toBits() on string in...`. Not even `toHex()` works. Please fix :)
