### ISSUE TITLE
Library does not support php 8.0.1

### ISSUE THREAD

**Issue by mitmelon** [jenssegers/imagehash#68]
I got this error when trying to use composer for updating

    - Root composer.json requires jenssegers/imagehash ^0.7.0 -> satisfiable by
jenssegers/imagehash[v0.7.0].
    - jenssegers/imagehash v0.7.0 requires php ^7.0 -> your php version (8.0.1
does not satisfy that requirement.

**Comment by sinedoOo** [comment]
Temporary solution:

`composer install --ignore-platform-reqs`

**Comment by jdreesen** [comment]
Or better yet: `composer install --ignore-platform-req=php` which only ingores platform requirements for PHP itself (needs composer 2, though).

**Comment by sinedoOo** [comment]
Any update here?
