### ISSUE TITLE
Support for intervention/image ^3.0

### ISSUE THREAD

**Issue by pataar** [jenssegers/imagehash#85]
Intervention Image version 3.0 has been released. We use intervention/image seperately in our project unfortunately this package blocks the upgrade of intervention/image. 

Is it possible to upgrade intervention/image to version 3 in this project? I could try to make a PR if you want?

**Comment by jenssegers** [comment]
A PR would be great!

**Comment by pataar** [comment]
Created pr #86

**Comment by pataar** [comment]
@jenssegers The new major requires PHP 8.1. What's your opinion about bumping the minimum PHP version of your package to the same version?

**Comment by ekstrakt** [comment]
@jenssegers any news?
