### ISSUE TITLE
class not found error

### ISSUE THREAD

**Issue by php1webmobtech** [jenssegers/imagehash#9]
Please help.I run in local this package but i getting Fatal error: Class 'Jenssegers\ImageHash\Implementations\DifferenceHash' not found in /opt/lampp/htdocs/demo/imagehash-master/src/ImageHash.php on line 26

why I getting this error ?Please give answer.

**Comment by wouterds** [comment]
@php1webmobtech Did you run `composer install` & include the autoloader? It's a bit vague, a bit more info would be welcome.

**Comment by wouterds** [comment]
Ah, there is something wrong in the documentation indeed.

It says

$implementation = new Jenssegers\ImageHash\Implementation\DifferenceHash;

while it should be

$implementation = new Jenssegers\ImageHash\Implementation*s*\DifferenceHash;

Try this demo script:
	<?php

	include('vendor/autoload.php');

	$implementation = new Jenssegers\ImageHash\Implementations\DifferenceHash;
	$hasher = new Jenssegers\ImageHash\ImageHash($implementation);
	$hash = $hasher->hash('image1.jpg');

	echo 'Hash: ' . $hash;

**Comment by jenssegers** [comment]
Thanks @wouterds!
